version: '3.8'
services:
  mariadb:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root#*#505
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_admin
      MYSQL_PASSWORD: WPadmin@123
    ports:
      - "3308:3306"
  wordpress:
    depends_on: 
      - mariadb
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    ports:
      - "80:80"